@startsalt
scale 2
skinparam backgroundColor white
{
{T
+ **topic** | **payload** | **retain** | **msg exp**
+ apc
++ **apc_static**
+++ [Provider ID]
++++ spaces
+++++ [spaceId] | PASSENGER SPACE | True | not set (inf)
++++ sensor_entrance_mappings
+++++ [sensorId-entranceId] | sensorId-entranceId mapping | True | not set (inf)
++++ entrance_entrance_mappings
+++++ [entranceId1-enctranceId2] | entranceId1-entranceId2 mapping | True | not set (inf)
++ **entrance_counts**
+++ [Provider ID]
++++ [sensorId] OR [entranceId] | PASSENGER ENTRANCE COUNT | False? | ?
++ **space_counts**
+++ [Provider ID]
++++ space_entrance_counts
+++++ [spaceId] | PASSENGER SPACE ENTRANCE COUNT | False? | ?
++++ space_occupancy_counts
+++++ [spaceId] | PASSENGER SPACE OCCUPANCY COUNT | False? | ?
+++ space_occupancy_ratios
+++++ [spaceId] | PASSENGER SPACE OCCUPANCY RATIO | False? | ?
+++ reset_request
++++ [spaceId] or [spaceType] | passenger space count reset | True? | ?

}
}
@endsalt
